src/Entity/Produits.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProduitsRepository")
 */
class Produits
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $titre;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="float")
     */
    private $prix;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Categories", inversedBy="produits")
     */
    private $categorie;

    /**
     * @ORM\Column(type="boolean")
     */
    private $disponibilite;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Tva", inversedBy="produits")
     */
    private $tva;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $quantity;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(?string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getFormatedPrice() : string
    {
      return number_format($this-> prix, 0, '', ' ');
    }

    public function getCategorie(): ?Categories
    {
        return $this->categorie;
    }

    public function setCategorie(?Categories $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }
    
    public function __toString()
    {
        return $this->titre;
    }

    public function getDisponibilite(): ?bool
    {
        return $this->disponibilite;
    }

    public function setDisponibilite(bool $disponibilite): self
    {
        $this->disponibilite = $disponibilite;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getTva(): ?tva
    {
        return $this->tva;
    }

    public function setTva(?tva $tva): self
    {
        $this->tva = $tva;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(?int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

}

src/Controller/ShowController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Produits;
use App\Entity\Categories;


class ShowController extends AbstractController
{


    // /**
    //  * @Route("/categorie", name="categorie")
    //  */
    // public function categorie()
    // {
         

    //      $repo = $this->getDoctrine()->getRepository(Categories::class);
    //      $categories = $repo->findAll();



    //     return $this->render('show/index.html.twig', [
    //         // 'controller_name' => 'HomeController',
    //         'controller_name' => 'ShowController',

            
    //         'categories' => $categories
    //     ]);
    // }


    // /**
    //  * @Route("/categorie/{id}", name="show")
    //  */
    // public function index($id)
    // {
    //     $repo = $this->getDoctrine()->getRepository(Produits::class);
    //     $produit = $repo->find($id);

    //     return $this->render('show/index.html.twig', [
    //         'controller_name' => 'ShowController',
    //         'produit' => $produit
    //     ]);
    // }




}

templates/show/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{produit.titre}}{% endblock %}
{% block description %}{{produit.description}}{% endblock %}

{% block body %}

<div class="d-flex flex-wrap">
  <div class="col-3 mt-5 pt-5">
    <img class="card-img-top" src="{{produit.image}}" alt="">
  </div>
  <div class="col-6 mt-5 pt-5">
     <h3 class="card-title">{{produit.titre}}</h3>
      <h4>{{produit.formatedPrice | tva (produit.tva.multiplicateur)}} €</h4>
      <p class="card-text">{{produit.description}}</p>
      <div>
        Description, date de livraison, si en stock ou non, ect.
      </div>
  </div>
  <div class="col-3 mt-5">
    <div class="col-8 mt-5 card">
      {% if panier[produit.id] is not defined  %}
      {{ form_start(form) }}
        <div class="col-10 offset-1 mb-3">
          {{form_row(form.quantity, {'attr': {'placeholder':'Veillez entrer une quantité', 'class':'form-control'}})}}
        </div>
        <div class="col-12 mb-3">
          {{form_row(form.ajoutPanier, {'attr': {'class':'form-control btn-primary'}})}}
        </div>
      {{form_end(form)}}
      {% else %}
        <div>
          <a href="{{path ('panier')}}" class="btn btn-primary">Le produit est déja dans votre panier</a>              
        </div>
      {% endif %} 
    </div>
  </div>
  <div class="col-12 mt-5">
    <h3 class="pl-3">Autres produits proposés</h3>
    <div class="d-flex flex-wrap">
      <div class="col-3">
        <img class="pl-5 img-fluid" src="https://via.placeholder.com/240x240" />
      </div>
      <div class="col-3">
        <img class="pl-5 img-fluid" src="https://via.placeholder.com/240x240" />
      </div>
      <div class="col-3">
        <img class="pl-5 img-fluid" src="https://via.placeholder.com/240x240" />
      </div>
      <div class="col-3">
        <img class="pl-5 img-fluid" src="https://via.placeholder.com/240x240" />
      </div>
    </div>
  </div>
</div>
          
{% endblock %}